### ISSUE TITLE
Link to accumulated solidity<>Clarity pair dataset

### ISSUE THREAD

**Issue by mali-tintash** [Markeljan/smart-contract-gpt#1]
Can you please provide a link to the pair dataset of solidity to clarity conversion that you used for this?

**Comment by Markeljan** [comment]
Hey @mali-tintash here are the prompts.  GPT-4 already has good context regarding Solidity so just needed to provide Clarity.

System Prompts with Clarity contract examples:
[lib/prompts.ts ](https://github.com/Markeljan/smart-contract-gpt/blob/ea7f69bd3286dc65640e3b177b3c16dde9c8b8ad/lib/prompts.ts)
